name: "Release Build"

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: 'The server and web release tag ("vX.Y.Z") or "master"'

permissions:
  contents: read

jobs:
  checkoutRepository:
    runs-on: ubuntu-22.04
    steps:
      - name: "Install dependencies"
        run: |-
          sudo apt-get install --yes python3-git

      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Prepare Repository"
        run: |-
          ./checkout.py ${{ github.event.client_payload.version }}

  buildDebianPackages:
    runs-on: ubuntu-22.04
    needs:
      - checkoutRepository
    strategy:
      matrix:
        version:
          - 11
          - 12
        arch:
          - amd64
          - arm64
          - armhf
    steps:
      - name: "Run builder for Debian ${{ matrix.version }} ${{ matrix.arch }}"
        run: |-
          sudo ./build.py ${{ github.event.client_payload.version }} debian ${{ matrix.arch }} ${{ matrix.version }}
